### ISSUE TITLE
CVEs in golang included in examples

### ISSUE THREAD

**Issue by mdnorman** [DataDog/datadog-cdk-constructs#283]
## Expected Behavior

Including this library shouldn't cause containers to have CVEs.

## Actual Behavior

There are several CVEs present in the version of golang included in the examples.

## Steps to Reproduce the Problem

  1. Create a container
  1. Scan the container for security vulnerabilities

## Specifications

  - Datadog CDK Constructs v2 version: 1.14.1
  - Node version: 20.17.0

**Comment by lym953** [comment]
Looking

**Comment by lym953** [comment]
@mdnorman I'm unable to reproduce the problem. Could you elaborate on how you reproduced it, and what CVEs you saw?

**Comment by mdnorman** [comment]
AWS Inspector is highlighting several High severity warnings for our account from using datadog packages. Here are screenshots for just 3 of them. The first couple are directly from the Datadog CDK Constructs library, whereas the next couple of are from the datadog-agent extension that I think uses the library:

<img width="645" alt="datadog-cve-1" src="https://github.com/user-attachments/assets/c65c1d33-3cfa-4acb-8eb7-98c5866c1b6d">
<img width="623" alt="datadog-cve-2" src="https://github.com/user-attachments/assets/8164bf05-e27a-4844-9389-9674d2478981">
<img width="627" alt="datadog-cve-3" src="https://github.com/user-attachments/assets/1c962d78-e3ab-4bb5-ba65-f39ccda96234">
<img width="633" alt="datadog-cve-4" src="https://github.com/user-attachments/assets/745cfeb5-9a7c-48a5-b94e-f927fd1fbbe9">

**Comment by lym953** [comment]
@mdnorman Thanks for the details. I created a container image using the example Go stack and scanned it with Amazon Inspector, but I don't see any vulnerability related to the `datadog-cdk-constructs-go` package. Most vulnerabilities are from the `jsii-runtime-go` package.

Since you mentioned some of the vulnerabilities you found are from the example Go stack, I removed the example stack from the latest package release v1.16.0. Could you retry with this version? Let me know if you have any further finding.

> the datadog-agent extension that I think uses the library

I don't think this is true as far as I know.

**Comment by purple4reina** [comment]
@mdnorman Let us know if this change removes those CVEs for you. If not, feel free to reopen this issue.
